CREATE TABLE patients (
    patient_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custFN           VARCHAR2(50) NOT NULL,
    custLN           VARCHAR2(50) NOT NULL,
    bloodGroup       VARCHAR2(5),
    address          VARCHAR2(255) NOT NULL
);

CREATE TABLE branches (
    branch_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch           VARCHAR2(100) NOT NULL
);

CREATE TABLE treatments (
    treatment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis        VARCHAR2(255) NOT NULL UNIQUE,
    treatmentCost    NUMBER(10, 2) NOT NULL
);

CREATE TABLE departments (
    dept_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department       VARCHAR2(100) NOT NULL
);

CREATE TABLE staff (
    staff_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_name       VARCHAR2(100) NOT NULL,
    role             VARCHAR2(50) NOT NULL,
    hourly_rate      NUMBER(10, 2) NOT NULL
);

CREATE TABLE shifts_roster (
    shift_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id         NUMBER NOT NULL,
    dept_id          NUMBER NOT NULL,
    shift_date       DATE NOT NULL,
    shift_type       VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_shift_staff FOREIGN KEY (staff_id) REFERENCES staff(staff_id),
    CONSTRAINT fk_shift_dept  FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);

CREATE TABLE encounters (
    uniqueID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       NUMBER NOT NULL,
    branch_id        NUMBER NOT NULL,
    treatment_id     NUMBER NOT NULL,
    createdOn        TIMESTAMP DEFAULT SYSTIMESTAMP,
    type             VARCHAR2(2) NOT NULL,
    CONSTRAINT chk_enc_type CHECK (type IN ('ER', 'IP', 'OP')),
    CONSTRAINT fk_enc_patient   FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    CONSTRAINT fk_enc_branch    FOREIGN KEY (branch_id) REFERENCES branches(branch_id),
    CONSTRAINT fk_enc_treatment FOREIGN KEY (treatment_id) REFERENCES treatments(treatment_id)
);

CREATE TABLE treatment_logs (
    uniqueID         NUMBER NOT NULL,
    visits           NUMBER NOT NULL,
    dept_id          NUMBER NOT NULL,
    staff_id         NUMBER NOT NULL,
    roomNum          VARCHAR2(20),
    VAS              NUMBER(2),
    total            NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_treatment_logs PRIMARY KEY (uniqueID, visits),
    CONSTRAINT fk_log_encounter FOREIGN KEY (uniqueID) REFERENCES encounters(uniqueID),
    CONSTRAINT fk_log_dept      FOREIGN KEY (dept_id) REFERENCES departments(dept_id),
    CONSTRAINT fk_log_staff     FOREIGN KEY (staff_id) REFERENCES staff(staff_id)
);