
  CREATE TABLE "TREATMENT_LOGS" 
   (	"UNIQUEID" NUMBER NOT NULL ENABLE, 
	"VISITS" NUMBER NOT NULL ENABLE, 
	"DEPT_ID" NUMBER NOT NULL ENABLE, 
	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"ROOMNUM" VARCHAR2(20), 
	"TOTAL" NUMBER(10,2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TREATMENT_LOGS" PRIMARY KEY ("UNIQUEID", "VISITS")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "TREATMENT_LOGS" ADD CONSTRAINT "FK_LOG_DEPT" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENTS" ("DEPT_ID") ENABLE;
  ALTER TABLE "TREATMENT_LOGS" ADD CONSTRAINT "FK_LOG_ENCOUNTER" FOREIGN KEY ("UNIQUEID")
	  REFERENCES "ENCOUNTERS" ("UNIQUEID") ENABLE;
  ALTER TABLE "TREATMENT_LOGS" ADD CONSTRAINT "FK_LOG_STAFF" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "STAFF" ("STAFF_ID") ENABLE;